services:
  db:
    image: postgres:latest
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: imoveisSA
    ports:
      - '5432:5432'