spring.application.name=ImoveisSA

spring.datasource.url=jdbc:postgresql://localhost:5432/imoveisSA
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create